services:
  krakend:
    image: ${REGISTRY:-thechief28}/api-gateway-krakend:${IMAGE_TAG:-latest-${LOCAL_ARCH:-x86}}  # Use ARCH variable to select the correct image
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=KrakenD API Gateway
    command: [ "run", "-dc", "/etc/krakend/krakend.json", "" ]
