services:
  krakend:
    image: ${REGISTRY:-992382520594.dkr.ecr.ap-southeast-3.amazonaws.com}/api-gateway/krakend:${IMAGE_TAG:-latest-${LOCAL_ARCH:-x86}} # Default to the provided values or use defaults
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=KrakenD API Gateway
    command: [ "run", "-dc", "/etc/krakend/krakend.json", "" ]
