name: Build and Push Image to Docker Hub (Production)

on:
  push:
    tags: ['v*.*.*']

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-push-production-docker:
    name: Build and Push image to Docker Hub (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.13.0'

      # - name: Install Python dependencies
      #   run: make install-python-deps

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.1'
        id: install

      - name: Build and push Docker image using Makefile
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: api-gateway-krakend
          IMAGE_TAG: ${{ github.ref_name }}
        run: make docker-build-push-prod

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Current tag is ${{ github.ref_name }}"

      - name: Clone GitOps repository
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git clone https://$GH_USERNAME:$GH_PERSONAL_ACCESS_TOKEN@github.com/anandakevin/vault-infra-manifests.git
        env:
          GITOPS_REPO_URL: https://github.com/anandakevin/vault-infra-manifests.git
          GITOPS_REPO: vault-infra-manifests
          GH_USERNAME: ${{secrets.GH_USERNAME}}
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      
      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize

      - name: Update Kustomize image tag
        run: |
          cd $GITOPS_REPO/k8s/api-gateway/krakend/service/krakend/overlays/production-docker
          kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/api-gateway-krakend:$IMAGE_TAG
        env: 
          GITOPS_REPO: vault-infra-manifests
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Build Kubernetes manifests using Kustomize
        run: |
          cd $GITOPS_REPO
          make kustomize-krakend-docker-prod
        env: 
          GITOPS_REPO: vault-infra-manifests

      - name: Commit and Push changes to GitOps repo
        run: |
          cd $GITOPS_REPO
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .  # Stage the updated YAML file
          git commit -m "Update api-gateway/krakend production docker image tag in deployment.yaml to $IMAGE_TAG"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/anandakevin/vault-infra-manifests.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN  }}  # Token for authentication
          GITOPS_REPO: vault-infra-manifests
          IMAGE_TAG: ${{ github.ref_name }}


